name: Render_Deployment

on:
  push:
    branches: main

jobs:
  deploy_to_render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trigger Render Deployment
      run: |
        curl -X POST "$RENDER_DEPLOY_HOOK"
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}